# Safe manifest.yml read/write using PyYAML.
#
# Values are treated as Python data — yaml.dump() handles all YAML
# serialization including proper quoting of special characters.
# No string interpolation, no regex substitution, no injection risk.

from pathlib import Path
import yaml

MANIFEST_PATH = ".specify/manifest.yml"
SDD_VERSION   = "2.6.0"


def read_manifest(path: str = MANIFEST_PATH) -> dict | None:
    p = Path(path)
    if not p.exists():
        return None
    return yaml.safe_load(p.read_text()) or {}


def write_manifest(manifest: dict, path: str = MANIFEST_PATH) -> None:
    header = (
        f"# SDD Manifest — generated by sdd-init v{SDD_VERSION}\n"
        "# See QUICKSTART.md for field documentation\n"
    )
    Path(path).write_text(
        header + yaml.dump(manifest, default_flow_style=False, allow_unicode=True)
    )


def patch_manifest(patches: dict, path: str = MANIFEST_PATH) -> dict:
    manifest = read_manifest(path)
    if manifest is None:
        raise FileNotFoundError(f"{path} not found — are you in the pack root?")

    # Deep-merge patches into manifest
    for key, value in patches.items():
        if isinstance(value, dict) and isinstance(manifest.get(key), dict):
            manifest[key] = {**manifest[key], **value}
        else:
            manifest[key] = value

    write_manifest(manifest, path)
    return manifest
