# Safe manifest.yml read/write using PyYAML.
#
# Values are treated as Python data — yaml.dump() handles all YAML
# serialization including proper quoting of special characters.
# No string interpolation, no regex substitution, no injection risk.
from __future__ import annotations

from pathlib import Path

import yaml

from sdd import __version__ as SDD_VERSION
from sdd.utils.atomic_write import atomic_write_text, read_text_resilient

MANIFEST_PATH = ".specify/manifest.yml"
# SDD_VERSION is the single source of truth for "what version is this" —
# it IS the installed sddflow package version (sdd --version), not a
# separate counter. manifest.yml's sdd_version field is just a stamp of
# this same number, so `sdd --version` and a freshly-generated manifest
# never show two different numbers.


class ManifestError(Exception):
    """manifest.yml exists but isn't valid YAML -- deliberately distinct
    from a *missing* manifest (read_manifest returns None for that, which
    every caller already treats as "no project here yet"). A corrupt
    manifest means the project clearly does exist, so silently treating it
    the same as "absent" risks a caller re-scaffolding over it or quietly
    dropping real config -- raise loudly instead, with a message that
    actually says what to do about it."""


def read_manifest(path: str = MANIFEST_PATH) -> dict | None:
    p = Path(path)
    if not p.exists():
        return None
    try:
        text, repaired = read_text_resilient(p)
    except UnicodeDecodeError as e:
        raise ManifestError(
            f"{path} isn't valid UTF-8, and isn't valid Windows-1252 "
            f"either: {e}\n"
            "This usually means the file was written by an sdd "
            "version older than 3.7.1 on a non-UTF-8 system locale. "
            "Fix it by hand, restore it from git history, or delete "
            "it to start over with a fresh `sdd init`."
        ) from e
    try:
        manifest = yaml.safe_load(text) or {}
    except yaml.YAMLError as e:
        raise ManifestError(
            f"{path} exists but isn't valid YAML: {e}\n"
            "Fix it by hand, restore it from git history, or delete it to "
            "start over with a fresh `sdd init` -- nothing does that for "
            "you automatically."
        ) from e
    if repaired:
        # Self-heal: rewrite this exact text, just properly UTF-8 encoded
        # now, so every other command reading this file stops hitting the
        # same crash too -- this only needs to happen once. Writing back
        # the original text (not write_manifest()'s re-serialized
        # yaml.dump()) preserves any hand-added comments/formatting
        # byte-for-byte instead of silently discarding them.
        atomic_write_text(path, text)
    return manifest


def write_manifest(manifest: dict, path: str = MANIFEST_PATH) -> None:
    header = (
        f"# SDD Manifest — schema v{SDD_VERSION} (generated by sddflow)\n"
        "# See QUICKSTART.md for field documentation\n"
    )
    content = header + yaml.dump(manifest, default_flow_style=False, allow_unicode=True)

    # Atomic write matters here specifically: every command reads this
    # file, so a process killed mid-write (e.g. `sdd upgrade` interrupted)
    # leaving manifest.yml truncated breaks the whole project, not just
    # the interrupted command.
    atomic_write_text(path, content)


def patch_manifest(patches: dict, path: str = MANIFEST_PATH) -> dict:
    manifest = read_manifest(path)
    if manifest is None:
        raise FileNotFoundError(f"{path} not found — are you in the pack root?")

    # Deep-merge patches into manifest
    for key, value in patches.items():
        if isinstance(value, dict) and isinstance(manifest.get(key), dict):
            manifest[key] = {**manifest[key], **value}
        else:
            manifest[key] = value

    write_manifest(manifest, path)
    return manifest
