# Unit tests for sdd.utils.validate — name validation and feature-path containment.
from pathlib import Path

import pytest

from sdd.utils.validate import (
    validate_name,
    assert_valid_name,
    safe_feature_path,
    resolve_doc_path,
    LIVING_SERVICE_DOCS,
    PROJECT_SCOPED_DOCS,
)


def test_validate_name_rejects_empty():
    assert validate_name("", "Feature") is not None
    assert validate_name("   ", "Feature") is not None


def test_validate_name_rejects_double_quote():
    assert validate_name('foo"bar', "Feature") is not None


def test_validate_name_accepts_normal_name():
    assert validate_name("payments", "Feature") is None


def test_assert_valid_name_raises_on_invalid():
    with pytest.raises(ValueError):
        assert_valid_name("", "Feature")


def test_safe_feature_path_rejects_empty():
    with pytest.raises(ValueError):
        safe_feature_path(Path(".specify") / "features", "")


def test_safe_feature_path_accepts_normal_name(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    result = safe_feature_path(Path(".specify") / "features", "payments")
    assert result == Path(".specify") / "features" / "payments"


def test_safe_feature_path_rejects_parent_traversal(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    with pytest.raises(ValueError):
        safe_feature_path(Path(".specify") / "features", "../../../../tmp/pwned")


def test_safe_feature_path_rejects_sibling_prefix_bypass(tmp_path, monkeypatch):
    """A feature name that resolves to a sibling directory whose name merely
    starts with the same string as the base directory (e.g. base 'features',
    sibling 'features-legacy') must be rejected — a naive string-prefix
    check without a separator boundary would incorrectly allow this."""
    monkeypatch.chdir(tmp_path)
    with pytest.raises(ValueError):
        safe_feature_path(Path(".specify") / "features", "../features-legacy")


def test_safe_feature_path_rejects_sibling_prefix_bypass_variant(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    with pytest.raises(ValueError):
        safe_feature_path(Path(".specify") / "features", "../features_backup")


def test_resolve_doc_path_routes_living_docs_to_service_dir(tmp_path, monkeypatch):
    """data-model/security-design/api-spec must resolve to
    .specify/service/{doc}.md regardless of which feature is active —
    this is what lets a second feature find and extend the first
    feature's schema/API/security baseline instead of getting a blank
    per-feature copy."""
    monkeypatch.chdir(tmp_path)
    for doc in LIVING_SERVICE_DOCS:
        for feature in ("instant-payment", "payment-dashboard", ""):
            assert (
                resolve_doc_path(doc, feature)
                == Path(".specify") / "service" / f"{doc}.md"
            )


def test_resolve_doc_path_routes_constitution_to_memory_dir(tmp_path, monkeypatch):
    """constitution.md lives at .specify/memory/constitution.md -- outside
    both .specify/features/ and .specify/service/ -- regardless of which
    feature is active, since it's project-wide (Part 1 universal, Part 2
    amended in place across every feature)."""
    monkeypatch.chdir(tmp_path)
    for feature in ("instant-payment", "payment-dashboard", ""):
        assert resolve_doc_path("constitution", feature) == (
            Path(".specify") / "memory" / "constitution.md"
        )


def test_resolve_doc_path_keeps_other_docs_per_feature(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    assert resolve_doc_path("design", "payment-dashboard") == (
        Path(".specify") / "features" / "payment-dashboard" / "design.md"
    )
    assert resolve_doc_path("context", "payment-dashboard") == (
        Path(".specify") / "contexts" / "payment-dashboard.md"
    )
    # Traversal protection still applies to the per-feature path
    with pytest.raises(ValueError):
        resolve_doc_path("design", "../../../../tmp/pwned")


def test_resolve_doc_path_routes_runbook_to_docs_dir(tmp_path, monkeypatch):
    """runbook.md is a living artifact generated by /implement (not
    /specify-doc), and unlike LIVING_SERVICE_DOCS it doesn't live under
    .specify/service/ -- it's docs/runbook/local-setup.md, regardless of
    which feature is active. Getting this wrong is what let `sdd review
    submit --doc runbook` silently resolve to a nonexistent
    .specify/features/{feature}/runbook.md path."""
    monkeypatch.chdir(tmp_path)
    for feature in ("instant-payment", "payment-dashboard", ""):
        assert resolve_doc_path("runbook", feature) == (
            Path("docs") / "runbook" / "local-setup.md"
        )


def test_project_scoped_docs_includes_constitution_runbook_and_living_docs():
    assert PROJECT_SCOPED_DOCS == LIVING_SERVICE_DOCS | {"constitution", "runbook"}
