// Safe manifest.yml read/write using js-yaml.
//
// Values are treated as JS data — js-yaml handles all YAML serialization
// including proper escaping of special characters. No string interpolation,
// no regex substitution, no injection risk.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import yaml from 'js-yaml';

export const MANIFEST_PATH = '.specify/manifest.yml';
export const SDD_VERSION   = '2.7.0';

export function readManifest(path = MANIFEST_PATH) {
  if (!existsSync(path)) return null;
  return yaml.load(readFileSync(path, 'utf8'));
}

export function writeManifest(manifest, path = MANIFEST_PATH) {
  const header = `# SDD Manifest — schema v${SDD_VERSION} (generated by sddflow)\n` +
                 `# See QUICKSTART.md for field documentation\n`;
  writeFileSync(path, header + yaml.dump(manifest, {
    lineWidth: -1,
    quotingType: '"',
  }));
}

export function patchManifest(patches, path = MANIFEST_PATH) {
  const manifest = readManifest(path);
  if (!manifest) throw new Error(`${path} not found — are you in the pack root?`);

  // Deep-merge patches into manifest
  for (const [key, value] of Object.entries(patches)) {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      manifest[key] = { ...manifest[key], ...value };
    } else {
      manifest[key] = value;
    }
  }

  writeManifest(manifest, path);
  return manifest;
}
