// Safe manifest.yml read/write using js-yaml.
//
// Values are treated as JS data — js-yaml handles all YAML serialization
// including proper escaping of special characters. No string interpolation,
// no regex substitution, no injection risk.

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createRequire } from 'module';
// Namespace import, not a default import -- js-yaml 5.x dropped its
// default export (ESM-only change; `load`/`dump` are still named exports),
// so `import yaml from 'js-yaml'` throws SyntaxError under 5.x while still
// silently working under 4.x. This form is resilient to either.
import * as yaml from 'js-yaml';

const require = createRequire(import.meta.url);
const { version: SDD_VERSION } = require('../../package.json');

export const MANIFEST_PATH = '.specify/manifest.yml';
// SDD_VERSION is the single source of truth for "what version is this" —
// it IS the installed sddflow package version (sdd --version), not a
// separate counter. manifest.yml's sdd_version field is just a stamp of
// this same number, so `sdd --version` and a freshly-generated manifest
// never show two different numbers.
export { SDD_VERSION };

export function readManifest(path = MANIFEST_PATH) {
  if (!existsSync(path)) return null;
  return yaml.load(readFileSync(path, 'utf8'));
}

export function writeManifest(manifest, path = MANIFEST_PATH) {
  const header = `# SDD Manifest — schema v${SDD_VERSION} (generated by sddflow)\n` +
                 `# See QUICKSTART.md for field documentation\n`;
  writeFileSync(path, header + yaml.dump(manifest, {
    lineWidth: -1,
    quotingType: '"',
  }));
}

export function patchManifest(patches, path = MANIFEST_PATH) {
  const manifest = readManifest(path);
  if (!manifest) throw new Error(`${path} not found — are you in the pack root?`);

  // Deep-merge patches into manifest
  for (const [key, value] of Object.entries(patches)) {
    if (typeof value === 'object' && value !== null && !Array.isArray(value)) {
      manifest[key] = { ...manifest[key], ...value };
    } else {
      manifest[key] = value;
    }
  }

  writeManifest(manifest, path);
  return manifest;
}
